import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import CustomSessionProvider from "./clientComponents/SessionProvider"
import {Noto_Serif}  from "next/font/google"
import Footer from "./clientComponents/Footer";
import Navbar from "./clientComponents/Navbar";

import {Toaster}  from "react-hot-toast"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const notofont = Noto_Serif({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Watchify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notofont.className} antialiased`}
      >
        <CustomSessionProvider>
        <Toaster
  position="top-center"
  reverseOrder={false}
/>      
<Navbar/> 
<div className="min-h-[70vh]">
{children}

</div>
<Footer/>

        </CustomSessionProvider>
      </body>
    </html>
  );
}
